### PR TITLE
Hotfix - Generated Tailwind CSS code for flags

### PR DESCRIPTION
**Pull request by ByMykel**
Fix for #46.

### CODE REVIEW

**Comment by markmead** [comment]
Great spot and in fact, this PR can fix a little more than this as the `JIT` check is outdated.

The first thing to change would be the `direction` prop to no longer be required.

```js
direction: {
  type: [String, Boolean],
  default: false
},
```

And then we can swap the check for `this.version === 'JIT'` out for something that works.

```js
return this.currentDirection
  ? `${this.currentDirection} ${this.colors}`
  : `${this.colors}`
```

And that should fix it.

**Review by markmead — CHANGES_REQUESTED** [review]
Few things to fix but a great PR as this is legacy code that we no longer need!

**Comment by ByMykel** [comment]
@markmead Should I remove the `this.version` condition or check if it's true to return the `this.css`?

**Comment by markmead** [comment]
Nice, thanks for that! 

I'm just waiting for @jordihales to update the Node version on Vercel so we can have deployment previews.

**Comment by jordihales** [comment]
Just update Vercel to Node v16.x so should be good to go @markmead 

Thanks again @ByMykel great PR!

**Review by markmead — APPROVED** [review]
Doesn't seem like Vercel wants to redeploy, but that's OK, I can see the code is working fine.

**Pull request merged**
